version: '3.3'

services:
  db-node:
    build:
      context: pgsql
      dockerfile: Dockerfile
    container_name: db-node
    restart: unless-stopped
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: hstiv
      POSTGRES_PASSWORD: 112233qq
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - db-node-data:/var/lib/mysql

  proxysql:
    build:
      context: proxysql
      dockerfile: Dockerfile
    container_name: proxysql
    depends_on:
      - "db-node"
    command: >
      --initial
    volumes:
      - proxysql-data:/var/lib/proxysql
    networks:
      - default
    ports:
      # Mysql Client Port
      - "6033:6033"
      # Mysql Admin Port
      - "6032:6032"

volumes:
  db-node:
  proxysql-data:

networks:
  default:
    driver: "bridge"
    external: false